// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    INotoGirlArtist: typeof import('~icons/noto/girl-artist')['default']
    INotoPaint: typeof import('~icons/noto/paint')['default']
    INotoPaintbrush: typeof import('~icons/noto/paintbrush')['default']
    INotoPainter: typeof import('~icons/noto/painter')['default']
    INotoPalette: typeof import('~icons/noto/palette')['default']
    INotoWomanArtist: typeof import('~icons/noto/woman-artist')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
